# Use an official Python runtime as the base image
FROM python:3.11-slim

ENV PIP_NO_CACHE_DIR=off
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=utf-8
ENV LC_ALL=C.UTF-8
ENV LANG=en_US.UTF-8

COPY . .

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install poetry && \
    poetry install --no-root --no-dev && \
    poetry export --without-hashes --without dev -o requirements.txt && \
    pip uninstall -y poetry \ 
    pip install -r requirements.txt

RUN apt install build-essential pkg-config libasound2-dev git

RUN git clone https://github.com/gbevin/SendMIDI.git

RUN cd SendMIDI && cd Builds/LinuxMakeFile && make && mv build/sendmidi /usr/local/bin
# Expose port 8000 for the Django app (adjust as needed)
EXPOSE 8000

# Run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]