# Generated by Django 5.1.5 on 2025-02-03 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miditheatre", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="settingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light Mode"), ("dark", "Dark Mode")],
                        max_length=10,
                    ),
                ),
                (
                    "go_key",
                    models.IntegerField(
                        help_text="Keycode for 'Go' action",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(256),
                        ],
                    ),
                ),
                (
                    "stop_key",
                    models.IntegerField(
                        help_text="Keycode for 'Stop' action",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(256),
                        ],
                    ),
                ),
            ],
        ),
    ]
