# Generated by Django 5.1.5 on 2025-02-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miditheatre", "0002_settinguser"),
    ]

    operations = [
        migrations.CreateModel(
            name="actionPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255, unique=True)),
                ("parent", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
