# Generated by Django 5.1.5 on 2025-02-04 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miditheatre", "0003_actionpath"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="miditheatre.actionpath",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="actionpath",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="miditheatre.actionpath",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="action",
            unique_together={("path", "name")},
        ),
    ]
