# Generated by Django 5.1.5 on 2025-02-04 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miditheatre", "0004_action_path_alter_action_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("actions", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="action",
            options={},
        ),
        migrations.RemoveField(
            model_name="action",
            name="order",
        ),
        migrations.AddField(
            model_name="settinguser",
            name="show_current",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="miditheatre.show",
            ),
        ),
    ]
