# Generated by Django 5.1.5 on 2025-02-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miditheatre", "0005_show_alter_action_options_remove_action_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
