# Generated by Django 5.1.5 on 2025-02-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("miditheatre", "0006_alter_show_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="actionpath",
            unique_together={("category", "parent")},
        ),
    ]
