# Generated by Django 5.1.5 on 2025-02-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miditheatre", "0007_alter_actionpath_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="actions",
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
