# Generated by Django 5.1.5 on 2025-02-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miditheatre", "0008_alter_show_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="selected_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="miditheatre.action",
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="actions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
