# Generated by Django 5.1.5 on 2025-02-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miditheatre", "0009_show_selected_action_alter_show_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
