# Generated by Django 5.1.5 on 2025-02-05 19:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miditheatre", "0010_alter_action_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
