# Generated by Django 5.1.5 on 2025-02-11 03:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miditheatre", "0012_alter_action_channel_alter_show_selected_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="link_tracker",
            fields=[
                (
                    "linked_actions",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
