from miditheatre.extras.logger import LOGGER

def keycode_to_name(keycode:int) -> str:
    char = chr(keycode)
    altchars = {
        '\r': 'ENTER',
        '\t': 'TAB',
        ' ': 'SPACE',
        '\x1b': 'ESC',
        '\x7f': 'DEL',
        '\x1b[A': 'UP',
        '\x1b[B': 'DOWN',
        '\x1b[C': 'RIGHT',
        '\x1b[D': 'LEFT',
        '\x1b[3~': 'DEL',
        '\x1b[5~': 'PAGE_UP',
        '\x1b[6~': 'PAGE_DOWN',
        '\x1b[7~': 'HOME',
        '\x1b[8~': 'END',
        '\x1b[11~': 'F1',
        '\x1b[12~': 'F2',
        '\x1b[13~': 'F3',
        '\x1b[14~': 'F4',
        '\x1b[15~': 'F5',
        '\x1b[17~': 'F6',
        '\x1b[18~': 'F7',
        '\x1b[19~': 'F8',
        '\x1b[20~': 'F9',
        '\x1b[21~': 'F10',
        '\x1b[23~': 'F11',
        '\x1b[24~': 'F12',
        '\x1b[2~': 'INSERT',
        '\x1b[1~': 'HOME',
        '\x1b[4~': 'END',
        '\x1b[H': 'HOME',
        '\x1b[F': 'END',
        '\x1b[Z': 'SHIFT_TAB',
        '\x1b[25~': 'F13',
        '\x1b[26~': 'F14',
        '\x1b[28~': 'F15',
        '\x1b[29~': 'F16',
        '\x1b[31~': 'F17',
        '\x1b[32~': 'F18',
        '\x1b[33~': 'F19',
        '\x1b[34~': 'F20',
    }
    return 'Key: "{}"'.format(altchars.get(char, char))